services:
  webrtc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrtc_app
    ports:
      - "127.0.0.1:8080:8080" # Binds port 8080 only to localhost for secure proxying via Nginx
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  coturn:
    image: coturn/coturn:latest
    container_name: coturn_server
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "50000-50010:50000-50010/udp"
    command:
      - -n
      - --log-file=stdout
      - --min-port=50000
      - --max-port=50010
      - --realm=simplevoip.local
      - --user=voipuser:voippassword
      - --fingerprint
      - --lt-cred-mech
    restart: always
